"use client";
import { useState } from "react";
import ClubNavigation from "../components/dashboard/ClubNavigation";
import styles from "./tests.module.css";
type Check={subject:string; topic:string; cadence:string; format:string; pass:string; due:string};
const CHECKS:Check[]=[
{subject:"Mathematics",topic:"Rates, percentages & problem solving",cadence:"Weekly 15 min",format:"6 retrieval questions + 1 word problem",pass:"5/6 + explain method",due:"Friday"},
{subject:"English",topic:"Reading, grammar & written response",cadence:"Weekly 20 min",format:"Read, annotate, then write",pass:"Clear evidence + 70%",due:"Thursday"},
{subject:"Science",topic:"Forces, living systems or current unit",cadence:"Weekly priority",format:"Explain + labelled diagram",pass:"4/5 concepts accurate",due:"Wednesday"},
{subject:"HASS",topic:"Geography, civics & economics",cadence:"Fortnightly 25 min",format:"Map/source + short argument",pass:"3 evidence-backed points",due:"Week 2 Friday"},
{subject:"Turkish",topic:"Vocabulary, listening & spoken recall",cadence:"Twice weekly 10 min",format:"Say, hear, use",pass:"8/10 recall",due:"Tue + Thu"},
{subject:"Quranic Arabic",topic:"Al-Kahf vocabulary & recitation",cadence:"Twice weekly 10 min",format:"Recite + meaning match",pass:"8/10 + calm recitation",due:"Mon + Thu"},
{subject:"Digital skills",topic:"Mac workflow, ecom & marketing",cadence:"Fortnightly build",format:"Ship a small useful artefact",pass:"Works + can explain it",due:"Friday"},
{subject:"Chess",topic:"Tactics & game review",cadence:"Weekly 15 min",format:"3 puzzles + 1 reviewed game",pass:"2/3 solved with reason",due:"Sunday"}];
export default function TestsPage(){const [active,setActive]=useState(CHECKS[0]);const [result,setResult]=useState<string|undefined>();const [filter,setFilter]=useState("All");const shown=filter==="All"?CHECKS:CHECKS.filter(c=>c.subject===filter);return <main className={styles.page} aria-label="ANSAR OS Tests"><ClubNavigation activeLabel="Tests"/><section className={styles.content}><header><p>ANSAR OS · ASSESSMENT ROOM</p><h1>Train. Check. Learn. Rebuild.</h1><span>Short checks guide the next lesson. Unit exams prove what stayed.</span></header><div className={styles.principles}><b>Weekly retrieval</b><b>Fortnightly skill check</b><b>End-of-unit exam</b><b>Term review</b></div><div className={styles.filter}><button onClick={()=>setFilter("All")} className={filter==="All"?styles.selected:""}>All learning</button>{CHECKS.map(c=><button key={c.subject} onClick={()=>setFilter(c.subject)} className={filter===c.subject?styles.selected:""}>{c.subject}</button>)}</div><div className={styles.grid}>{shown.map(c=><button className={active.subject===c.subject?styles.active:""} onClick={()=>{setActive(c);setResult(undefined)}} key={c.subject}><span>{c.cadence}</span><b>{c.subject}</b><small>{c.due}</small></button>)}</div><section className={styles.station}><div><p>NEXT ASSESSMENT</p><h2>{active.subject}</h2><strong>{active.topic}</strong><dl><div><dt>Format</dt><dd>{active.format}</dd></div><div><dt>Pass standard</dt><dd>{active.pass}</dd></div><div><dt>Schedule</dt><dd>{active.cadence} · {active.due}</dd></div></dl></div><aside><p>Parent control</p><button onClick={()=>setResult("Passed — move to the next skill")}>Record pass</button><button onClick={()=>setResult("Rebuild — teach the gap, then re-sit in 3 days")}>Needs rebuild</button><button onClick={()=>setResult("Second miss — parent chooses a proportionate privilege pause after the re-teach")}>Second miss</button>{result?<strong className={styles.result}>{result}</strong>:<small>First miss never earns a consequence. It earns targeted teaching and a fresh attempt.</small>}</aside></section><section className={styles.protocol}><h2>The assessment protocol</h2><ol><li><b>Teach and practise first.</b> Give the study material and make success clear.</li><li><b>Short check.</b> Record the score, evidence and the exact gap.</li><li><b>Rebuild and re-sit.</b> A first miss means more teaching, then a new attempt within three days.</li><li><b>Parent decision.</b> Only a second miss after support may pause a chosen privilege; never make it automatic or humiliating.</li></ol></section></section></main>}
